#! /bin/sh

set -e

# The following only on a new install
if [ "$1" = "configure" ]; then
  echo "Configure"
  # The following only on a new install
  if [ "$2" = "" ]; then
    echo "First time install"
  fi

fi

chmod -R 666 /opt/huayra-duino-lr/*.ini
chmod 777 /opt/huayra-duino-lr/ArdublocklySketch
chmod 666 /opt/huayra-duino-lr/ArdublocklySketch/*
 
exit 0
#DEBHELPER#
