#! /bin/sh

set -e

# The following only on a new install
if [ "$1" = "configure" ]; then
  echo "Configure"
  # The following only on a new install
  if [ "$2" = "" ]; then
    echo "First time install"
  fi

fi

chmod -R 666 /usr/lib/huayra-duino-lr/resources/app/*.ini
chmod 777 /usr/lib/huayra-duino-lr/resources/app/ArdublocklySketch
chmod 666 /usr/lib/huayra-duino-lr/resources/app/ArdublocklySketch/*
 
exit 0
#DEBHELPER#
